---
- hosts: localhost
  connection: local
  become: true
  tasks:

    - name: update all packages
      ansible.builtin.apt:
        upgrade: dist
        update-cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"
